const YUHONAS_BASE = 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises';

const EX_IMG_MAP: Record<string,string> = {
  'Crossover polia alta':'Cable_Crossover',
  'Crucifixo inclinado halteres':'Incline_Dumbbell_Flyes',
  'Crucifixo Máquina':'Butterfly',
  'Crucifixo reto halteres':'Dumbbell_Flyes',
  'Flexão de braço':'Pushups',
  'Pullover halteres':'Bent-Arm_Dumbbell_Pullover',
  'Supino declinado barra':'Decline_Barbell_Bench_Press',
  'Supino declinado halteres':'Decline_Dumbbell_Bench_Press',
  'Supino inclinado barra':'Barbell_Incline_Bench_Press_-_Medium_Grip',
  'Supino inclinado halteres':'Dumbbell_Incline_Shoulder_Raise',
  'Supino reto barra':'Barbell_Bench_Press_-_Medium_Grip',
  'Supino reto halteres':'Dumbbell_Bench_Press',
  'Barra fixa':'Pullups',
  'Extensão lombar máquina':'Hyperextensions_Back_Extensions',
  'Pulldown':'Rope_Straight-Arm_Pulldown',
  'Puxada alta aberta':'Wide-Grip_Lat_Pulldown',
  'Puxada fechada':'Close-Grip_Front_Lat_Pulldown',
  'Puxada triângulo':'V-Bar_Pulldown',
  'Remada articulada':'Leverage_Iso_Row',
  'Remada baixa polia':'Seated_Cable_Rows',
  'Remada cavalinho':'Bent_Over_Two-Arm_Long_Bar_Row',
  'Remada curvada barra':'Barbell_Rear_Delt_Row',
  'Remada curvada halteres':'Bent_Over_Two-Dumbbell_Row',
  'Remada serrote halteres':'One-Arm_Dumbbell_Row',
  'Levantamento terra':'Barbell_Deadlift',
  'Arnold press halteres':'Arnold_Dumbbell_Press',
  'Crucifixo inverso halteres':'Reverse_Flyes',
  'Crucifixo inverso máquina':'Reverse_Machine_Flyes',
  'Desenvolvimento barra':'Barbell_Shoulder_Press',
  'Desenvolvimento halteres':'Dumbbell_Shoulder_Press',
  'Desenvolvimento máquina':'Leverage_Shoulder_Press',
  'Elevação frontal halteres':'Front_Dumbbell_Raise',
  'Elevação lateral halteres':'Side_Lateral_Raise',
  'Elevação lateral polia':'Cable_Seated_Lateral_Raise',
  'Face Pull corda':'Face_Pull',
  'Encolhimento barra':'Barbell_Shrug',
  'Encolhimento halteres':'Dumbbell_Shrug',
  'Rosca alternada halteres':'Dumbbell_Alternate_Bicep_Curl',
  'Rosca concentrada halteres':'Concentration_Curls',
  'Rosca direta barra':'Barbell_Curl',
  'Rosca direta halteres':'Dumbbell_Bicep_Curl',
  'Rosca martelo halteres':'Hammer_Curls',
  'Rosca Scott máquina':'Machine_Preacher_Curls',
  'Rosca Bayesian cabo':'Standing_Biceps_Cable_Curl',
  'Kick back tríceps halteres':'Standing_Bent-Over_One-Arm_Dumbbell_Triceps_Extension',
  'Mergulho no banco':'Bench_Dips',
  'Paralelas':'Dips_-_Triceps_Version',
  'Tríceps francês barra':'Standing_Overhead_Barbell_Triceps_Extension',
  'Tríceps francês halteres':'Standing_Dumbbell_Triceps_Extension',
  'Tríceps pulley barra reta':'Triceps_Pushdown',
  'Tríceps pulley corda':'Triceps_Pushdown_-_Rope_Attachment',
  'Tríceps testa barra W':'Lying_Close-Grip_Barbell_Triceps_Press_To_Chin',
  'Afundo com halteres':'Dumbbell_Lunges',
  'Agachamento búlgaro halteres':'Split_Squat_with_Dumbbells',
  'Agachamento hack máquina':'Hack_Squat',
  'Agachamento livre':'Barbell_Squat',
  'Agachamento sumô barra':'Barbell_Side_Split_Squat',
  'Agachamento sumô halteres':'Dumbbell_Squat',
  'Cadeira extensora':'Leg_Extensions',
  'Cadeira flexora':'Seated_Leg_Curl',
  'Leg press 45':'Leg_Press',
  'Mesa flexora':'Lying_Leg_Curls',
  'Passada avançada halteres':'Dumbbell_Lunges',
  'Stiff':'Stiff-Legged_Barbell_Deadlift',
  'Stiff barra':'Stiff-Legged_Barbell_Deadlift',
  'Stiff com halteres':'Stiff-Legged_Dumbbell_Deadlift',
  'Abdução em pé polia':'Cable_Hip_Adduction',
  'Cadeira abdutora':'Thigh_Abductor',
  'Elevação pélvica com barra':'Barbell_Hip_Thrust',
  'Hip Thrust barra':'Barbell_Hip_Thrust',
  'Hip Thrust máquina':'Barbell_Hip_Thrust',
  'Glúteo 4 apoios cabo':'One-Legged_Cable_Kickback',
  'Panturrilha em pé máquina':'Standing_Calf_Raises',
  'Panturrilha sentado':'Seated_Calf_Raise',
  'Panturrilha sentado máquina':'Seated_Calf_Raise',
  'Abdominal crunch':'Crunches',
  'Abdominal máquina':'Crunches',
  'Prancha':'Plank',
  'Prancha isométrica':'Plank',
};

export function getGifUrls(name: string): {url0:string;url1:string}|null {
  const slug = EX_IMG_MAP[name];
  if(!slug) return null;
  return {
    url0: `${YUHONAS_BASE}/${slug}/0.jpg`,
    url1: `${YUHONAS_BASE}/${slug}/1.jpg`,
  };
}
